apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - name: quarkus
        image: arthurdbs/challenge-01:latest
        ports:
        - containerPort: 8080
