apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-triggerbinding
      template:
        ref: pipeline-template
