apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhook-role
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get", "list", "watch"]
