apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6IllYSjBhSFZ5WkdKek9rQkJjakZFTkVJeSIsImVtYWlsIjoidGh1cmRpYXNAZ21haWwuY29tIn19fQ==%
